PlataformaIEB/Controllers/AutenticarController.cs
using PlataformaIEB.Models;
using PlataformaIEB.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace PlataformaIEB.Controllers
{
    public class AutenticarController : Controller
    {
        
        BancoDeDados db = new BancoDeDados();

        public ActionResult Login()
        {
            VMLogin login = new VMLogin();
            return View("Login",login);

        }

        private bool VerificaSenha(VMLogin login, Usuario usuario)
        {
            if (!Crypto.VerifyHashedPassword(usuario.Senha, login.Senha))
            {
                return false;
            }

            //Gera Aleatório Cadastro Usuario (TOkken)
            string autoriza = Guid.NewGuid().ToString();

            //Salva Tokken no Banco
            usuario.AutID = autoriza;
            db.SaveChanges();

            //Cria Cookie da identificação
            var CookieTokken = new HttpCookie("TokkenCookie");
            CookieTokken.Expires = DateTime.Now.AddDays(1);
            CookieTokken.Value = autoriza;
            Response.Cookies.Add(CookieTokken);
            Session["Tokken"] = CookieTokken;

            //Cria Cookie de nome de Usuário
            var CookieNome = new HttpCookie("CookieNome");
            CookieNome.Expires = DateTime.Now.AddDays(1);
            CookieNome.Value = usuario.Nome;
            Response.Cookies.Add(CookieNome);
            Session["Tokken"] = CookieNome;


            //Cria Cookie de tipo de Usuário
            var CookieTipo = new HttpCookie("CookieTipo");
            CookieTipo.Expires = DateTime.Now.AddDays(1);
            CookieTipo.Value = ProcuraUsuario(autoriza).ToString();
            Response.Cookies.Add(CookieTipo);
            Session["Tokken"] = CookieTipo;

            return true;
        }


        private Tipo ProcuraUsuario(string AutID)
        {
            if (db.Medicos.Where(b => b.AutID == AutID).FirstOrDefault() != null)
            {
                return Tipo.Medico;
            }
            if (db.Admins.Where(a => a.AutID == AutID).FirstOrDefault() != null)
            {
                return Tipo.ADMIN;
            }
            if (db.Pacientes.Where(c => c.AutID == AutID).FirstOrDefault() != null)
            {
                return Tipo.Paciente;
            }
            if (db.Pesquisadores.Where(c => c.AutID == AutID).FirstOrDefault() != null)
            {
                return Tipo.Pesquisador;
            }

            return Tipo.Paciente;
        }

        public enum Tipo { Pesquisador, Medico, Paciente, ADMIN}

        [HttpPost]
        public ActionResult Login(VMLogin login)
        {
            if (ModelState.IsValid)
            {
                Usuario usuario = db.Usuarios.Where(a => login.Email == a.Email).SingleOrDefault();

                if (VerificaSenha(login, usuario))
                {
                    return RedirectToAction("Principal", "Home", new { area = "" });
                }

                ModelState.AddModelError("", "Falha no Login! Favor entrar em contato");
                return View(login);
            }

            ModelState.AddModelError("", "Falha no Login! Favor entrar em contato");
            return View(login);

        }

        public ActionResult Logout()
        {
            if (Request.Cookies.AllKeys.Contains("TokkenCookie"))
            {
                String AutID = Request.Cookies["TokkenCookie"].Value;
                Usuario usuario = db.Usuarios.Where(a=>a.AutID == AutID).SingleOrDefault();
                if(usuario != null)
                {
                    usuario.AutID = null;
                    db.SaveChanges();
                }

                Request.Cookies["TokkenCookie"].Value = "";
                Request.Cookies["TokkenCookie"].Expires = DateTime.Now;
                Response.SetCookie(Request.Cookies["TokkenCookie"]);

                Request.Cookies["CookieNome"].Value = "";
                Request.Cookies["CookieNome"].Expires = DateTime.Now;
                Response.SetCookie(Request.Cookies["CookieNome"]);

                Request.Cookies["CookieTipo"].Value = "";
                Request.Cookies["CookieTipo"].Expires = DateTime.Now;
                Response.SetCookie(Request.Cookies["CookieTipo"]);

            }

            ViewBag.Sucesso = false;

            Request.Cookies.Clear();
            return RedirectToAction("Index","Home");
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            Pesquisador Pesquisa = new Pesquisador();
            return View(Pesquisa);
        }


        [HttpPost]
        public ActionResult Cadastrar(Pesquisador Pesquisa)
        {
            if (ModelState.IsValid)
            {
                Pesquisa.Senha = Crypto.HashPassword(Pesquisa.Senha.ToString());
                db.Pesquisadores.Add(Pesquisa);
                db.SaveChanges();

                return RedirectToAction("Login");
            }

            return View(Pesquisa);
        }

    }
}

PlataformaIEB/Controllers/CadastroController.cs
using PlataformaIEB.Filtros;
using PlataformaIEB.Models;
using PlataformaIEB.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace PlataformaIEB.Controllers
{

    public class CadastroController : Controller
    {

        BancoDeDados db = new BancoDeDados();

        public int CalculaIdade(DateTime Nascimento)
        {
            int idade = DateTime.Now.Year - Nascimento.Year;

            if ((Nascimento.Month > DateTime.Now.Month) || (Nascimento.Month == DateTime.Now.Month && Nascimento.Day > DateTime.Now.Day))
                idade--;

            return idade;
        }


        [LiberarAreas(4)]
        public ActionResult PrincipalMedico(string busca)
        {
            if (string.IsNullOrEmpty(busca))
            {
                busca = "";
            }

            List<Medico> TodosMedicos = db.Medicos.Where(a => a.Nome.Contains(busca)).OrderBy(a => a.Nome).ToList();
            return PartialView(TodosMedicos);
        }

        [LiberarAreas(4)]
        [HttpGet]
        public ActionResult CadMedico()
        {
            return View();
        }

        [LiberarAreas(4)]
        [HttpPost]
        public ActionResult CadMedico(Medico medico)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    medico.Senha = Crypto.HashPassword(medico.Senha.ToString());
                    db.Medicos.Add(medico);
                    db.SaveChanges();
                    return Redirect(Request.UrlReferrer.ToString());
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Email em uso");
                    return View(medico);
                }

            }

            return View(medico);
        }

        [LiberarAreas(3)]
        [HttpGet]
        public ActionResult EditMedico(int Id)
        {
            ViewBag.TituloPainel = "Editar Informações";
            var medico = db.Medicos.Where(m => m.Id == Id).FirstOrDefault();
            return View(medico);
        }

        [LiberarAreas(3)]
        [HttpPost]
        public ActionResult EditMedico(Medico medico)
        {
            if (ModelState.IsValid)
            {
                db.Medicos.AddOrUpdate(medico);
                db.SaveChanges();
                return RedirectToAction("PrincipalMedico");

            }
            return View(medico);
        }

        [LiberarAreas(3)]
        public ActionResult PrincipalPaciente(string busca)
        {
            if (string.IsNullOrEmpty(busca))
            {
                busca = "";
            }
            List<Paciente> TodosPacientes = db.Pacientes.Where(a => a.Nome.Contains(busca)).OrderBy(p => p.Nome).ToList();
            return PartialView(TodosPacientes);
        }


        [LiberarAreas(3)]
        [HttpGet]
        public ActionResult CadPaciente()
        {
            ViewBag.Titulo = "Cadastro de Paciente";
            Paciente paciente = new Paciente();
            ViewBag.Sexo = new List<string>
            {
                "Masculino",
                "Feminino"
            };
            return View();

        }


        [LiberarAreas(3)]
        [HttpPost]
        public ActionResult CadPaciente(Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    paciente.Senha = Crypto.HashPassword(paciente.Senha.ToString());
                    db.Pacientes.Add(paciente);
                    db.SaveChanges();
                    return RedirectToAction("CadPaciente");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Email em uso");
                    ViewBag.Sexo = new List<string>{"Masculino","Feminino"};
                    return View(paciente);
                }

            }

            ViewBag.Sexo = new List<string> { "Masculino", "Feminino" };
            return View(paciente);
        }

        [LiberarAreas(1)]
        [HttpGet]
        public ActionResult EditPaciente(int Id)
        {
            ViewBag.TituloPainel = "Editar Informações";
            Paciente paciente = db.Pacientes.Where(p => p.Id == Id).FirstOrDefault();
            ViewBag.Sexo = new List<string>
            {
                "Masculino",
                "Feminino"
            };
            return View(paciente);
        }

        [LiberarAreas(1)]
        [HttpPost]
        public ActionResult EditPaciente(Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                db.Pacientes.AddOrUpdate(paciente);
                db.SaveChanges();
                return RedirectToAction("PrincipalPaciente");
            }

            ViewBag.Sexo = new List<string>
            {
                "Masculino",
                "Feminino"
            };
            return View(paciente);
        }

        [LiberarAreas(3)]
        [HttpGet]
        public ActionResult CadConsulta()
        {
            var Tokken = Request.Cookies["TokkenCookie"].Value;
            Usuario usuario = db.Usuarios.Where(a => a.AutID == Tokken).SingleOrDefault();
            List<ListaValores> Valores = new List<ListaValores>();
            var Variaveis = db.Variaveis.Where(
                a => a.Base.Where(o => !o.Objetivo).Select(b => b.Base.Usuario.Id).Contains(usuario.Id) 
                || a.Nome == "Idade" || a.Nome == "Sexo");

            foreach (var item in Variaveis)
            {
                Valores.Add(new ListaValores() { Variavel = item, VariavelID = item.ID, Confianca = 100 });
            }

            VMConsulta Modelo = new VMConsulta() { Valores = Valores };
            Modelo.Pacientes = db.Pacientes.Select(a=>a.Nome).ToList();
            Modelo.Usuario = usuario;
            return View(Modelo);
        }

        [LiberarAreas(3)]
        [HttpPost]
        public ActionResult CadConsulta(VMConsulta Modelo)
        {
            if (Modelo.Nome != null)
            {
                Paciente paciente = db.Pacientes.Where(a => a.Nome == Modelo.Nome).SingleOrDefault();

                Consulta Consulta = new Consulta()
                {
                    Paciente = paciente,
                    Data = DateTime.Now,
                    Medico = db.Medicos.Where(a => a.Id == Modelo.Usuario.Id).SingleOrDefault(),
                    Observacao = Modelo.Observacao
                    
                };

                db.Consultas.Add(Consulta);

                var procPadrao = db.Variaveis.Where(a => a.Nome.Contains("Sexo") || a.Nome.Contains("Idade")).ToList();

                if (Modelo.Valores.Any() || !string.IsNullOrEmpty(Modelo.Observacao))
                {                   

                    foreach (var item in Modelo.Valores)
                    {
                        item.Valor = (item.VariavelID == procPadrao.Where(a => a.Nome.Contains("Sexo")).Select(a=>a.ID).Single() && item.Valor == null) ? paciente.Sexo : item.Valor;
                        item.Valor = (item.VariavelID == procPadrao.Where(a => a.Nome.Contains("Idade")).Select(a => a.ID).Single() && item.Valor == null) ? CalculaIdade(paciente.Nascimento).ToString() : item.Valor;

                        if (item.Valor != null)
                        {
                            item.Valor = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(item.Valor);
                            item.Consulta = Consulta;
                            item.ConsultaID = Consulta.ID;

                            item.Confianca = 100;

                            db.Valores.Add(item);
                        }
                    }
                }
                else
                {
                    Modelo.Pacientes = db.Pacientes.Select(a => a.Nome).ToList();
                    Modelo.Usuario = db.Usuarios.Where(a => a.Id == Modelo.Usuario.Id).SingleOrDefault();
                    ModelState.AddModelError("", "Nenhum dado de entrada");
                    return RedirectToAction("CadConsulta");
                }
                db.SaveChanges();
                try
                {
                    db.SaveChanges();

                    return RedirectToAction("Teste", Consulta);

                }
                catch (Exception)
                {
                    Modelo.Pacientes = db.Pacientes.Select(a => a.Nome).ToList();
                    Modelo.Usuario = db.Usuarios.Where(a => a.Id == Modelo.Usuario.Id).SingleOrDefault();
                    ModelState.AddModelError("", "Erro grave! Favor entrar em contato");
                    return View(Modelo);
                }
            }

            Modelo.Pacientes = db.Pacientes.Select(a => a.Nome).ToList();
            Modelo.Usuario = db.Usuarios.Where(a => a.Id == Modelo.Usuario.Id).SingleOrDefault();
            ModelState.AddModelError("", "Selecione um paciente");
            return RedirectToAction("CadConsulta");

        }

        [LiberarAreas(3)]
        public ActionResult Teste(Consulta Cons)
        {
            Cons = db.Consultas.Where(a=>a.ID == Cons.ID).FirstOrDefault();
            Buscador busca = new Buscador(Cons);
            busca.CriarAgentes();
            if (busca.Aplicadas.Count > 0)
            {
                VMTeste teste = new VMTeste();
                teste.Aplicadas = busca.Aplicadas.ToList();
                teste.Consulta = Cons;
                teste.Objetivos = db.Variaveis.Where(a => a.Base.Where(b => b.Base.Usuario.Id == Cons.Medico.Id).Select(b => b.Objetivo).Contains(true)).ToList();
                return View(teste);
            }

            return RedirectToAction("CadConsulta");
        }
    }

}

PlataformaIEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plataforma IEB-UFSC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'729ccdee-dfeb-4ed7-9042-fb370364282e'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-fixed-top navbar-light bg-light">
        <div class="container">
            @Html.ActionLink("Plataforma IEB-UFSC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="http://www.ieb.ufsc.br">Conheça o IEB-UFSC</a>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sobre", "About", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Contato", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>

                <ul class="nav navbar-nav ml-auto">
                    @{if (Request.Cookies.AllKeys.Contains("TokkenCookie"))
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Área do Usuário", "Principal", "Home", new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Sair", "Logout", "Autenticar", new { area = "" }, new { @class = "nav-link" })
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Entrar", "Login", "Autenticar", new { area = "" }, new { @class = "nav-link" })
                            </li>
                        }
                    }

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Plataforma IEB-UFSC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PlataformaIEB/Views/Shared/_LayoutADM.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plataforma IEB-UFSC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-fixed-top navbar-light bg-light">
        <div class="container">
            @Html.ActionLink("Plataforma IEB-UFSC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Profissionais", "CadMedico", "Cadastro", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Pacientes", "CadPaciente", "Cadastro", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sistema Especialista", "Base", "Especialista", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>

                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Área do Usuário", "Principal", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sair", "Logout", "Autenticar", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Plataforma IEB-UFSC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PlataformaIEB/Views/Shared/_LayoutMED.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plataforma IEB-UFSC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-fixed-top navbar-light bg-light">
        <div class="container">
            @Html.ActionLink("Plataforma IEB-UFSC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Pacientes", "CadPaciente", "Cadastro", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Consulta", "CadConsulta", "Cadastro", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sistema Especialista", "Base", "Especialista", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>

                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Área do Usuário", "Principal", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sair", "Logout", "Autenticar", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Plataforma IEB-UFSC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PlataformaIEB/Views/Shared/_LayoutPAC.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plataforma IEB-UFSC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-fixed-top navbar-light bg-light">
        <div class="container">
            @Html.ActionLink("Plataforma IEB-UFSC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Profissionais", "CadMedico", "Cadastro", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Pacientes", "CadPaciente", "Cadastro", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sistema Especialista", "Base", "Especialista", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>

                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Área do Usuário", "Principal", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sair", "Logout", "Autenticar", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Plataforma IEB-UFSC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PlataformaIEB/Views/Shared/_LayoutPES.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plataforma IEB-UFSC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-fixed-top navbar-light bg-light">
        <div class="container">
            @Html.ActionLink("Plataforma IEB-UFSC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Base de Conhecimento", "Base", "Especialista", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>

                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Área do Usuário", "Principal", "Home", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sair", "Logout", "Autenticar", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Plataforma IEB-UFSC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</body>
</html>