PlataformaIEB/Controllers/EspecialistaController.cs
using PlataformaIEB.Models;
using PlataformaIEB.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Migrations;
using PlataformaIEB.Filtros;
using System.Threading;
using System.Xml;
using System.Web.UI;

namespace PlataformaIEB.Controllers
{
    [LiberarAreas(2)]
    public class EspecialistaController : Controller
    {
        BancoDeDados dbSE = new BancoDeDados();

        public Usuario ProcuraUsuario()
        {

            string AutID = null;

            try
            {
                AutID = Request.Cookies["TokkenCookie"].Value;
            }
            catch (Exception)
            {

                return null; ;
            }
            

            return dbSE.Usuarios.Where(a => a.AutID == AutID).SingleOrDefault();

        }


        [HttpGet]
        public ActionResult Base()
        {
            VMBase VModel = new VMBase();
            Usuario usuario = ProcuraUsuario();
            if (usuario != null)
            {
                VModel.Bases = dbSE.Bases.Where(o => o.Usuario.Id == usuario.Id).ToList();
                VModel.Usuario = usuario.Id;
            }
            else return RedirectToAction("Login", "Autenticar", new { area = "" });
            return View(VModel);
        }

        [HttpPost]
        public ActionResult Base(VMBase Model)
        {
            if (ModelState.IsValid)
            {
                BaseDeConhecimento Base = new BaseDeConhecimento()
                {
                    Nome = Model.Nome,
                    Usuario = dbSE.Usuarios.Where(a => a.Id == Model.Usuario).SingleOrDefault()
                };

                dbSE.Bases.Add(Base);

                VarBase vinculaSexo = new VarBase { Variavel = dbSE.Variaveis.Where(o => o.Nome == "Sexo").SingleOrDefault(), Base = Base };
                dbSE.VarBase.Add(vinculaSexo);

                VarBase vinculaIdade = new VarBase { Variavel = dbSE.Variaveis.Where(o => o.Nome == "Idade").SingleOrDefault(), Base = Base };
                dbSE.VarBase.Add(vinculaIdade);

                dbSE.SaveChanges();

                return RedirectToAction("Variavel/" + Base.ID);

            }

            Model.Bases = dbSE.Bases.Where(o => o.Usuario.Id == Model.Usuario).ToList();
            return View(Model);
        }

        
        public ActionResult ExcluirBase(int ID)
        {
            BaseDeConhecimento Base = dbSE.Bases.Where(o => o.ID == ID).SingleOrDefault();
            ICollection<Variavel> Excluir = new List<Variavel>();

            dbSE.VarBase.RemoveRange(Base.Variaveis);

            if (Base.Regras != null)
            {
                foreach (var item in Base.Regras)
                {
                    dbSE.Cabecarios.Remove(item.Se);
                    dbSE.Cabecarios.RemoveRange(item.Conj.Select(a => a.Cabeca));
                    dbSE.ListConj.RemoveRange(item.Conj);

                    dbSE.Acoes.RemoveRange(item.Entao);
                }
                dbSE.Regras.RemoveRange(Base.Regras);
            }
            dbSE.Bases.Remove(Base);



            try
            {
                dbSE.SaveChanges();
                return RedirectToAction("Base");
            }       
            catch (Exception)
            {
                return JavaScript("alert('ERRO!');");
            }
        }

        public ActionResult ExcluirVar(int ID)
        {
            Variavel Variavel = dbSE.Variaveis.Where(o => o.ID == ID).SingleOrDefault();
            dbSE.VarBase.RemoveRange(Variavel.Base);

            try
            {
                dbSE.SaveChanges();
                return Redirect(Request.UrlReferrer.ToString());
            }
            catch (Exception)
            {
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        public List<string> CID(string termo)
        {
            List<string> Lista = new List<string>();
            string C10 = @"C:\PlataformaIEB\CID10\CID10.xml";
            string C0 = @"C:\PlataformaIEB\CID10\CID-O.xml";
            XmlDocument doc = new XmlDocument();
            doc.XmlResolver = new XmlUrlResolver();
            doc.Load(C0);
            var teste = doc.GetElementsByTagName("subcategoria");
            foreach (XmlNode item in teste)
            {
                var temp = item["nome"].InnerText;
                if (temp.ToLower().Contains(termo.ToLower())) Lista.Add(temp);
            }

            doc.Load(C10);
            teste = doc.GetElementsByTagName("subcategoria");
            foreach (XmlNode item in teste)
            {
                var temp = item["nome"].InnerText;
                if (temp.ToLower().Contains(termo.ToLower())) Lista.Add(temp);
            }

            return Lista;
        }

        public ActionResult ListaNomes(string term)
        {
            List<string> Nomes = new List<string>();
            Nomes.AddRange(dbSE.Variaveis.Select(o => o.Nome).Where(a=>a.ToLower().Contains(term.ToLower())));
            Nomes.AddRange(CID(term).Where(a => (Nomes.Count(b=> b==a ) < 1)));            
            //Nomes.RemoveAll(a => Nomes.Count(b => b == a) > 2);
            //Nomes = Nomes.Where(o=>o.ToUpper().Contains(term.ToUpper())).ToList();
            return Json(Nomes, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Variavel(int ID)
        {
            ViewBag.Base = dbSE.Bases.Where(a => a.ID == ID).Select(o=>o.Nome).SingleOrDefault();
            VMVar Modelo = new VMVar();
            Modelo.BaseID = ID;
            Modelo.Variaveis = dbSE.Variaveis.Where(o => o.Base.Select(a => a.Base.ID).Contains(ID)).ToList();

            return View(Modelo);
        }

        [HttpPost]
        public ActionResult Variavel(VMVar Modelo)
        {
            if (ModelState.IsValid)
            {
                Variavel var;

                try
                {
                    var = dbSE.Variaveis.Where(o => o.Nome == Modelo.Nome).Single();
                }
                catch (Exception)
                {
                    var = new Variavel();
                    var.Nome = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Modelo.Nome);
                    dbSE.Variaveis.AddOrUpdate(var);
                }

                VarBase referencia = new VarBase();
                referencia.Variavel = var;
                referencia.Base = dbSE.Bases.Where(a => a.ID == Modelo.BaseID).SingleOrDefault();
                referencia.Objetivo = Modelo.Obj;

                dbSE.VarBase.AddOrUpdate(referencia);

                try
                {
                    dbSE.SaveChanges();
                }
                catch (Exception)
                {
                    return RedirectToAction("Variavel/" + Modelo.BaseID); ;
                }


                return RedirectToAction("Variavel/" + Modelo.BaseID);
            }

            Modelo.Variaveis = dbSE.Variaveis.Where(o => o.Base.Select(a => a.Base.ID).Contains(Modelo.BaseID)).ToList();
            return View(Modelo);
        }

        [HttpGet]
        public ActionResult Regra(int ID)
        {

            ViewBag.Base = dbSE.Bases.Where(a => a.ID == ID).Select(o => o.Nome).SingleOrDefault();
            VMRegra Regra = new VMRegra();
            Regra.BaseID = ID;
            Regra.Regras = dbSE.Regras.Where(o => o.Base.ID == ID).ToList();
            Regra.Variaveis = dbSE.Variaveis.Where(o => o.Base.Select(a => a.Base.ID).Contains(ID)).Select(a => a.Nome).ToList();
            Regra.Operadores = new List<string>
            {
                "=","!=","<","<=",">",">="
            };
            return View(Regra);
        }

        [HttpPost]
        public ActionResult Regra(VMRegra Modelo)
        {
            if (ModelState.IsValid)
            {
                Cabecario Cabecario = new Cabecario();
                Cabecario.NOT = Modelo.Not;
                Cabecario.Operador = Modelo.Operador;
                Cabecario.Valor = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Modelo.Valor);
                Cabecario.Variavel = dbSE.Variaveis.Where(o => (o.Nome == Modelo.VarID)).SingleOrDefault();
                dbSE.Cabecarios.Add(Cabecario);

                Regra Regra = new Regra();
                Regra.Nome = Modelo.Nome;
                Regra.Se = Cabecario;
                Regra.Base = dbSE.Bases.Where(o => o.ID == Modelo.BaseID).SingleOrDefault();
                Regra.Se = Cabecario;

                dbSE.Regras.Add(Regra);
                dbSE.SaveChanges();

                return RedirectToAction("Cabeca/" + Regra.ID);

            }

            Modelo.Regras = dbSE.Regras.Where(o => o.Base.ID == Modelo.BaseID).ToList();
            Modelo.Variaveis = dbSE.Variaveis.Where(o => o.Base.Select(a => a.Base.ID).Contains(Modelo.BaseID)).Select(a => a.Nome).ToList();
            Modelo.Operadores = new List<string>
            {
                "=","!=","<","<=",">",">="
            };

            return View(Modelo);
        }

        public ActionResult ExcluirRegra(int ID)
        {
            Regra regra = dbSE.Regras.Where(a=> a.ID == ID).SingleOrDefault();
            var id = regra.Base.ID;
            dbSE.Cabecarios.Remove(regra.Se);
            dbSE.Cabecarios.RemoveRange(regra.Conj.Select(a => a.Cabeca));
            dbSE.ListConj.RemoveRange(regra.Conj);

            dbSE.Acoes.RemoveRange(regra.Entao);
            dbSE.Regras.Remove(regra);

            try
            {
                dbSE.SaveChanges();
                return RedirectToAction("Regra/"+id);
            }
            catch (Exception)
            {

                return Redirect(Request.UrlReferrer.ToString());
            }

        }


        [HttpGet]
        public ActionResult Cabeca(int ID)
        {
            VMRegra Modelo = new VMRegra();

PlataformaIEB/Views/Cadastro/CadConsulta.cshtml
@model PlataformaIEB.Models.VMConsulta

<head>
    <meta name="viewport" content="width=device-width" />

</head>

@{
    ViewBag.Title = "Cadastro de Médicos";
    switch (Request.Cookies["CookieTipo"].Value)
    {
        case "ADMIN":
            Layout = "~/Views/Shared/_LayoutADM.cshtml";
            break;

        case "Medico":
            Layout = "~/Views/Shared/_LayoutMED.cshtml";
            break;

        case "Pesquisador":
            Layout = "~/Views/Shared/_LayoutPES.cshtml";
            break;

        case "Paciente":
            Layout = "~/Views/Shared/_LayoutPAC.cshtml";
            break;
    }
}

<div class="jumbotron-fluid">
    <div class="card">
        <div class="card-header"><h3>Consulta</h3></div>
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.AntiForgeryToken()
                @Html.HiddenFor(a => a.Usuario.Id)

                <div class="form-group">
                    @Html.LabelFor(m => m.Pacientes)
                    @Html.DropDownListFor(m => m.Nome, new SelectList(Model.Pacientes), "Selecione o paciente ...", new { @class = "form-control" })
                    <span id="helpBlock2" class="help-block">
                        @Html.ValidationMessageFor(m => m.Nome)
                    </span>
                </div>
                @Html.Label("Variáveis")
                <div class="row">
                    @Html.ActionLink("Clique aqui para adicionar campos de registro (variáveis)", "Base", "Especialista", new { area = "" }, new { @class = "nav-link" })
                </div>
                <div class="card card-body">

                    <div class="form-group">
                        <div class="col">
                            @Html.EditorFor(model => model.Valores, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Valores, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col">
                        <textarea class="form-control" id="Observacao" name="Observacao" rows="5" style="min-width:100%"></textarea>
                            @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row justify-content-end">
                            <input type="submit" value="Salvar" class="btn btn-outline-success" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PlataformaIEB/Views/Cadastro/CadMedico.cshtml
@model PlataformaIEB.Models.Medico

<head>
    <meta name="viewport" content="width=device-width" />

</head>

@{
    ViewBag.Title = "Cadastro de Médicos";
    switch (Request.Cookies["CookieTipo"].Value)
    {
        case "ADMIN":
            Layout = "~/Views/Shared/_LayoutADM.cshtml";
            break;

        case "Medico":
            Layout = "~/Views/Shared/_LayoutMED.cshtml";
            break;

        case "Pesquisador":
            Layout = "~/Views/Shared/_LayoutPES.cshtml";
            break;

        case "Paciente":
            Layout = "~/Views/Shared/_LayoutPAC.cshtml";
            break;
    }
}

@section Scripts{
    <script>
        $("#AddressChecklistFilter").keyup(function (e) {
            $.ajax({
                url: '/Cadastro/PrincipalMedico',
                data: { busca: $("#AddressChecklistFilter").val() },
                success: function (msg) {
                    $("#Partial").html(msg);
                }
            })
        })

    </script>

    <script>
        $('#myModal').on('shown.bs.modal', function () {
            $('#myInput').trigger('focus')
        })
    </script>

}



<div class="container row">
    <div class="col-sm">
        <div class="card">
            <div class="card-header"><h3>Profissionais de Saúde</h3></div>
            <div class="card-body">
                <div class="row justify-content-center">
                    <input class="form-control" type="text" name="AddressChecklistFilter" id="AddressChecklistFilter" />
                </div>            
                <br /> 
                <div id="Partial">@Html.Action("PrincipalMedico")</div>
            </div>
        </div>
    </div>

    <div class="col-lg">
        <div class="jumbotron">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Novo Profisional de Saúde</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CRM, htmlAttributes: new { @class = "control-label col-md-10" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CRM, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CRM, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Instituicao, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Instituicao, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Instituicao, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Especialidade, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Especialidade, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Especialidade, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row justify-content-end">
                            <input type="submit" value="Adicionar" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>



</div>

PlataformaIEB/Views/Cadastro/CadPaciente.cshtml
@model PlataformaIEB.Models.Paciente

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>

<body>
    @{
        ViewBag.Title = "Cadastro de Pacientes";
        switch (Request.Cookies["CookieTipo"].Value)
        {
            case "ADMIN":
                Layout = "~/Views/Shared/_LayoutADM.cshtml";
                break;

            case "Medico":
                Layout = "~/Views/Shared/_LayoutMED.cshtml";
                break;

            case "Pesquisador":
                Layout = "~/Views/Shared/_LayoutPES.cshtml";
                break;

            case "Paciente":
                Layout = "~/Views/Shared/_LayoutPAC.cshtml";
                break;
        }
    }

    @section Scripts{
        <script>
            $("#AddressChecklistFilter").keyup(function (e) {
                $.ajax({
                    url: '/Cadastro/PrincipalPaciente',
                    data: { busca: $("#AddressChecklistFilter").val() },
                    success: function (msg) {
                        $("#Partial").html(msg);
                    }
                })
            })

        </script>

        <script>
            $('#myModal').on('shown.bs.modal', function () {
                $('#myInput').trigger('focus')
            })
        </script>

    }



    <div class="container row">
        <div class="col-sm">
            <div class="card">
                <div class="card-header"><h3>Pacientes</h3></div>
                <div class="card-body">
                    <div class="row justify-content-center">
                        <input class="form-control" type="text" name="AddressChecklistFilter" id="AddressChecklistFilter" />
                    </div>
                    <br />
                    <div id="Partial">@Html.Action("PrincipalPaciente")</div>
                </div>
            </div>
        </div>

        <div class="col-lg">
            <div class="jumbotron">
                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Novo Paciente</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Nascimento, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nascimento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nascimento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Responsavel, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Responsavel, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Responsavel, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Sexo, new SelectList(ViewBag.Sexo), "Selecione uma opção", new { @class = "form-control" } )
                                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row justify-content-end">
                                <input type="submit" value="Adicionar" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>

</body>
</html>

PlataformaIEB/Views/Cadastro/EditMedico.cshtml
@model PlataformaIEB.Models.Medico
@{
    ViewBag.Title = "Editar Informações";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
    <h3>Médico não encontrado</h3>
}
else
{
    <div class="row">
        <div class="col-md-offset-1">
            @using (Html.BeginForm())
            {
                @Html.Partial("_FormMedico", Model)

                <div class="form-group">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.Senha)
                    <input type="submit" class="btn btn-success" value="Salvar" />
                    @Html.ActionLink("Voltar", "PrincipalMedico", new { area = "Admin", Controller = "Cadastro" }, new { @class = "btn btn-danger" })
                </div>
            }
        </div>
    </div>
}

PlataformaIEB/Views/Cadastro/EditPaciente.cshtml
@model PlataformaIEB.Models.Paciente
@{
    ViewBag.Title = "EditPaciente";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
    <h3>Paciente não encontrado</h3>
}
else
{
    <div class="row">
        <div class="col-md-offset-1">
            @using (Html.BeginForm())
            {
                @Html.Partial("_FormPaciente", Model);

                <div class="form-group">
                    <div class="row">
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.Senha)
                        <input type="submit" class="btn btn-success" value="Salvar" />
                        @Html.ActionLink("Voltar", "PrincipalPaciente", new { area = "Admin", Controller = "Cadastro" }, new { @class = "btn btn-danger" })
                    </div>
                </div>


            }
        </div>
    </div>
}

PlataformaIEB/Views/Cadastro/PrincipalMedico.cshtml
@model List<PlataformaIEB.Models.Medico>

<div class="list-group pre-scrollable">
    @foreach (var item in Model)
    {
        <a class="list-group-item list-group-item-action" data-toggle="collapse" href="#@item.Id" role="button" aria-expanded="false" aria-controls="collapseExample">
            <h6>@item.Nome</h6>
        </a>
        <div class="collapse" id="@item.Id">
            <div class="card card-body">
                <nav class="nav flex-column">
                    <a class="nav-item nav-link" href="#" data-toggle="modal" data-target="#@item.Nome">Detalhes</a>
                    @Html.ActionLink("Excluir", "ExcluirCabeca/" + @item.Id, "Especialista", new { area = "" }, new { @class = "nav-item nav-link" })
                </nav>
            </div>
        </div>
        <div class="modal fade" id="@item.Nome" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Detalhes</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class=" col text-center">
                            <h4>@item.Nome</h4>
                            <div class="jumbotron lead">
                                <p>@Html.LabelFor(a => item.Email): @item.Email</p>
                                <p>@Html.LabelFor(a => item.Especialidade): @item.Especialidade</p>
                                <p>@Html.LabelFor(a => item.Instituicao): @item.Instituicao</p>
                                <p>@Html.LabelFor(a => item.Endereco): @item.Endereco</p>
                                <p>@Html.LabelFor(a => item.CRM): @item.CRM</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    }

</div>

PlataformaIEB/Views/Cadastro/PrincipalPaciente.cshtml
@model List<PlataformaIEB.Models.Paciente>

<div class="list-group pre-scrollable">
    @foreach (var item in Model)
    {
        <a class="list-group-item list-group-item-action" data-toggle="collapse" href="#@item.Id" role="button" aria-expanded="false" aria-controls="collapseExample">
            <h6>@item.Nome</h6>
        </a>
        <div class="collapse" id="@item.Id">
            <div class="card card-body">
                <nav class="nav flex-column">
                    <a class="nav-item nav-link" href="#" data-toggle="modal" data-target="#@item.Nome">Detalhes</a>
                    @Html.ActionLink("Excluir", "ExcluirCabeca/" + @item.Id, "Especialista", new { area = "" }, new { @class = "nav-item nav-link" })
                </nav>
            </div>
        </div>
        <div class="modal fade" id="@item.Nome" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Detalhes</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class=" col text-center">
                            <h4>@item.Nome</h4>
                            <div class="jumbotron lead">
                                <p>@Html.LabelFor(a => item.Nome): @item.Nome</p>
                                <p>@Html.LabelFor(a => item.Email): @item.Email</p>
                                <p>@Html.LabelFor(a => item.Nascimento): @item.Nascimento.Date.ToShortDateString()</p>
                                <p>@Html.LabelFor(a => item.Responsavel): @item.Responsavel</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    }

</div>